sonar.projectKey=yashjuneja
sonar.organization=yashjuneja

sonar.projectName=TestCiCd
sonar.projectVersion=1.0

# Source code
sonar.sources=.
sonar.exclusions=**/bin/**,**/obj/**

# Test project
sonar.tests=TestCiCd.Tests

# Coverage report path (we will generate this in pipeline)
sonar.cs.opencover.reportsPaths=**/TestResults/**/coverage.opencover.xml
